"""Additional BIS-sourced Indian Standards for the curated corpus.

Standard numbers, titles, sectional committees and ICS codes follow the Bureau of
Indian Standards catalogue (bis.gov.in / standards.bis.gov.in). Clause summaries are
condensed procurement-relevant paraphrases, not verbatim reproductions of the
copyrighted standard text.
"""

EXTRA_STANDARDS = [
    # ------------------------------------------------------------------ WATER
    {
        "id": "std-is-10500",
        "code": "IS 10500: 2012",
        "title": "Drinking Water - Specification",
        "category": "Water & Utilities",
        "technical_committee": "FAD 25 Drinking Water Sectional Committee",
        "ics_code": "13.060.20",
        "status": "current",
        "reaffirmation_year": 2022,
        "gazetted_date": "2012-05-01",
        "qco_mandatory": False,
        "scope": "Prescribes the acceptable limits and permissible limits in the absence of an alternate source for physical, chemical, bacteriological and radioactive parameters of drinking water supplied by public and packaged water systems.",
        "why_recommended_template": "Defines the potable water quality parameters that any water supply, treatment or distribution procurement must ultimately deliver.",
        "key_clauses": [
            {
                "clause_no": "Clause 4.1",
                "clause_title": "Organoleptic and Physical Parameters",
                "requirement_summary": "Turbidity, colour, odour, taste, pH and total dissolved solids must fall within the acceptable limits tabulated for drinking water.",
                "test_method": "IS 3025 (relevant parts) - Methods of sampling and test for water and wastewater",
                "tolerance_limit": "Turbidity acceptable limit 1 NTU (permissible 5 NTU); pH 6.5 to 8.5; TDS acceptable limit 500 mg/l.",
            },
            {
                "clause_no": "Clause 4.2",
                "clause_title": "General and Toxic Chemical Parameters",
                "requirement_summary": "Limits for total hardness, iron, chlorides, fluoride, arsenic, lead and other toxic substances shall not be exceeded.",
                "test_method": "IS 3025 series chemical analysis",
                "tolerance_limit": "Fluoride 1.0 mg/l acceptable (1.5 mg/l permissible); Arsenic 0.01 mg/l; Lead 0.01 mg/l.",
            },
            {
                "clause_no": "Clause 4.4",
                "clause_title": "Bacteriological Requirements",
                "requirement_summary": "Water in the distribution system shall be free from coliform organisms and E. coli.",
                "test_method": "IS 1622 - Methods of sampling and microbiological examination of water",
                "tolerance_limit": "Shall not be detectable in any 100 ml sample.",
            },
        ],
        "test_methods": [
            {"name": "Physico-chemical Analysis", "method_standard": "IS 3025 (Parts 1 to 64)", "frequency": "Batch / periodic surveillance", "mandatory": True},
            {"name": "Bacteriological Examination", "method_standard": "IS 1622", "frequency": "Routine surveillance", "mandatory": True},
        ],
        "amendments": [
            {"amendment_no": "Amendment No. 1", "date": "2015-06-01", "summary": "Revised limits and testing references for selected chemical parameters.", "status": "Active"},
            {"amendment_no": "Amendment No. 2", "date": "2021-09-01", "summary": "Editorial corrections and updated referenced test method parts.", "status": "Active"},
        ],
        "related_standards": [
            {"code": "IS 4984: 2016", "title": "Polyethylene Pipes for Water Supply", "relation_type": "Conveyance Material Standard"},
            {"code": "IS 8329: 2000", "title": "Ductile Iron Pressure Pipes", "relation_type": "Conveyance Material Standard"},
        ],
        "keywords": ["drinking water", "potable water", "water quality", "turbidity", "coliform", "fluoride", "TDS", "water supply"],
    },
    {
        "id": "std-is-7634-2",
        "code": "IS 7634 (Part 2): 2012",
        "title": "Code of Practice for Plastics Pipe Work for Potable Water Supplies - Laying and Jointing Polyethylene (PE) Pipes",
        "category": "Water & Utilities",
        "technical_committee": "PCD 26 Plastic Piping Systems Sectional Committee",
        "ics_code": "23.040.20",
        "status": "current",
        "reaffirmation_year": 2022,
        "gazetted_date": "2012-03-15",
        "qco_mandatory": False,
        "scope": "Covers recommended practice for handling, storage, trench preparation, laying, jointing (butt fusion, electrofusion and mechanical joints), testing and commissioning of polyethylene pipes used for potable water supply.",
        "why_recommended_template": "Governs installation workmanship, jointing technique qualification and hydrostatic field testing for any PE pipeline laying contract.",
        "key_clauses": [
            {
                "clause_no": "Clause 5",
                "clause_title": "Trench Preparation and Bedding",
                "requirement_summary": "Trench width, bedding material grading and cover depth shall be specified to protect the pipe from point loading and traffic loads.",
                "test_method": "Site inspection against laying drawings",
                "tolerance_limit": "Minimum cover 0.9 m under carriageway; bedding free from stones larger than 20 mm.",
            },
            {
                "clause_no": "Clause 7",
                "clause_title": "Butt Fusion and Electrofusion Jointing",
                "requirement_summary": "Jointing shall be carried out by trained operators using calibrated equipment with recorded fusion parameters.",
                "test_method": "Fusion parameter record review; destructive bend / peel test on trial joints",
                "tolerance_limit": "Trial joint shall show ductile failure outside the fusion zone.",
            },
            {
                "clause_no": "Clause 9",
                "clause_title": "Field Hydrostatic Pressure Test",
                "requirement_summary": "Completed pipeline sections shall be pressure tested before backfill acceptance and commissioning.",
                "test_method": "Field hydrostatic test with pressure-drop monitoring",
                "tolerance_limit": "Test pressure 1.5 times working pressure held without unacceptable pressure drop.",
            },
        ],
        "test_methods": [
            {"name": "Field Hydrostatic Pressure Test", "method_standard": "IS 7634 (Part 2) Clause 9", "frequency": "Every pipeline section", "mandatory": True},
            {"name": "Trial Joint Qualification", "method_standard": "IS 7634 (Part 2) Clause 7", "frequency": "Per operator / per machine", "mandatory": True},
        ],
        "amendments": [],
        "related_standards": [
            {"code": "IS 4984: 2016", "title": "Polyethylene Pipes for Water Supply", "relation_type": "Material Specification"},
            {"code": "IS 10500: 2012", "title": "Drinking Water - Specification", "relation_type": "Quality Outcome Standard"},
        ],
        "keywords": ["HDPE pipe laying", "butt fusion", "electrofusion", "pipeline", "water supply", "trench", "hydrostatic test", "jointing"],
    },
    {
        "id": "std-is-8329",
        "code": "IS 8329: 2000",
        "title": "Centrifugally Cast (Spun) Ductile Iron Pressure Pipes for Water, Gas and Sewage - Specification",
        "category": "Water & Utilities",
        "technical_committee": "MTD 6 Pig Iron and Cast Iron Sectional Committee",
        "ics_code": "23.040.10",
        "status": "current",
        "reaffirmation_year": 2021,
        "gazetted_date": "2000-11-20",
        "qco_mandatory": False,
        "scope": "Specifies requirements for centrifugally cast ductile iron pressure pipes with or without socket, in classes K7, K9 and K12, including dimensions, mechanical properties, cement mortar lining and external coating for water, gas and sewage conveyance.",
        "why_recommended_template": "Applies wherever ductile iron pressure mains are procured, fixing wall thickness class, mechanical properties and internal lining requirements.",
        "key_clauses": [
            {
                "clause_no": "Clause 6",
                "clause_title": "Wall Thickness Class",
                "requirement_summary": "Nominal wall thickness shall correspond to the declared class (K7 / K9 / K12) for the specified diameter.",
                "test_method": "Thickness measurement by ultrasonic or mechanical gauge",
                "tolerance_limit": "Class K9 nominal thickness with negative tolerance not exceeding (1.3 + 0.001 DN) mm.",
            },
            {
                "clause_no": "Clause 8",
                "clause_title": "Tensile and Elongation Requirements",
                "requirement_summary": "Ductile iron shall meet minimum tensile strength and elongation on test rings cut from production pipes.",
                "test_method": "Tensile test on machined test piece",
                "tolerance_limit": "Minimum tensile strength 420 MPa; minimum elongation 10 percent for centrifugally cast pipes.",
            },
            {
                "clause_no": "Clause 11",
                "clause_title": "Cement Mortar Lining and External Coating",
                "requirement_summary": "Internal cement mortar lining and external zinc plus bituminous coating shall be continuous and of specified thickness.",
                "test_method": "Lining thickness measurement and visual continuity check",
                "tolerance_limit": "Lining thickness as tabulated for the nominal diameter; no exposed metal or cracking.",
            },
        ],
        "test_methods": [
            {"name": "Hydrostatic Works Test", "method_standard": "IS 8329 Clause 10", "frequency": "Every pipe (routine)", "mandatory": True},
            {"name": "Tensile / Elongation Test", "method_standard": "IS 8329 Clause 8", "frequency": "Per casting lot", "mandatory": True},
            {"name": "Brinell Hardness Test", "method_standard": "IS 1500", "frequency": "Per lot", "mandatory": False},
        ],
        "amendments": [
            {"amendment_no": "Amendment No. 1", "date": "2003-05-01", "summary": "Clarified coating requirements and hydrostatic works test pressures.", "status": "Active"},
        ],
        "related_standards": [
            {"code": "IS 10500: 2012", "title": "Drinking Water - Specification", "relation_type": "Quality Outcome Standard"},
            {"code": "IS 4984: 2016", "title": "Polyethylene Pipes for Water Supply", "relation_type": "Alternative Material Standard"},
        ],
        "keywords": ["ductile iron pipe", "DI pipe", "K9", "pressure pipe", "sewage", "cement mortar lining", "water main"],
    },
    # ---------------------------------------------------------- ELECTROTECHNICAL
    {
        "id": "std-is-694",
        "code": "IS 694: 2010",
        "title": "Polyvinyl Chloride Insulated Unsheathed and Sheathed Cables/Cords with Rigid and Flexible Conductor for Voltages up to and including 450/750 V",
        "category": "Electrotechnical",
        "technical_committee": "ETD 9 Electrical Cables and Conductors Sectional Committee",
        "ics_code": "29.060.20",
        "status": "current",
        "reaffirmation_year": 2021,
        "gazetted_date": "2010-12-30",
        "qco_mandatory": True,
        "scope": "Specifies construction, dimensions and test requirements for PVC insulated cables and cords with copper or aluminium conductors for working voltages up to and including 450/750 V, used in internal wiring and equipment connection.",
        "why_recommended_template": "Applies to every low-voltage wiring cable procurement, fixing conductor resistance, insulation thickness and flammability requirements.",
        "key_clauses": [
            {
                "clause_no": "Clause 5",
                "clause_title": "Conductor Construction and Resistance",
                "requirement_summary": "Conductors shall be plain annealed copper or aluminium of the specified class with resistance not exceeding the tabulated maximum.",
                "test_method": "Conductor resistance measurement at 20 degree C",
                "tolerance_limit": "Maximum resistance per km as per IS 8130 for the declared conductor class and cross-section.",
            },
            {
                "clause_no": "Clause 7",
                "clause_title": "Insulation Thickness and Insulation Resistance",
                "requirement_summary": "Average and minimum insulation thickness shall meet the tabulated values and insulation resistance shall exceed the specified minimum.",
                "test_method": "Dimensional measurement and insulation resistance test",
                "tolerance_limit": "Minimum thickness not less than 90 percent of nominal minus 0.1 mm; insulation resistance above specified limit at 70 degree C.",
            },
            {
                "clause_no": "Clause 15",
                "clause_title": "Flammability Test",
                "requirement_summary": "Cables shall not propagate flame beyond the specified extent after the burner is removed.",
                "test_method": "Single vertical cable flammability test",
                "tolerance_limit": "Self-extinguishing within the limits given in the standard.",
            },
        ],
        "test_methods": [
            {"name": "High Voltage (Dielectric) Test", "method_standard": "IS 694 Clause 14", "frequency": "Routine test (all drums)", "mandatory": True},
            {"name": "Conductor Resistance Test", "method_standard": "IS 8130", "frequency": "Routine test", "mandatory": True},
            {"name": "Flammability Test", "method_standard": "IS 694 Clause 15", "frequency": "Type test", "mandatory": True},
        ],
        "amendments": [
            {"amendment_no": "Amendment No. 1", "date": "2015-03-01", "summary": "Aligned conductor classes and insulation test temperatures with IS 8130 revision.", "status": "Active"},
        ],
        "related_standards": [
            {"code": "IS 732: 2019", "title": "Code of Practice for Electrical Wiring Installations", "relation_type": "Installation Code"},
            {"code": "IS 3043: 2018", "title": "Code of Practice for Earthing", "relation_type": "Safety Code Complement"},
        ],
        "keywords": ["PVC cable", "wiring cable", "450/750 V", "copper conductor", "insulation resistance", "flammability", "LT cable"],
    },
    {
        "id": "std-is-732",
        "code": "IS 732: 2019",
        "title": "Code of Practice for Electrical Wiring Installations",
        "category": "Electrotechnical",
        "technical_committee": "ETD 20 Electrical Installations Sectional Committee",
        "ics_code": "91.140.50",
        "status": "current",
        "reaffirmation_year": 2024,
        "gazetted_date": "2019-04-25",
        "qco_mandatory": False,
        "scope": "Provides requirements for the design, selection of equipment, erection, verification and testing of electrical wiring installations in buildings for voltages not exceeding 1000 V AC, including protection against electric shock, thermal effects and overcurrent.",
        "why_recommended_template": "Sets the installation, protection and pre-commissioning verification requirements for any building electrical works package.",
        "key_clauses": [
            {
                "clause_no": "Clause 5",
                "clause_title": "Protection Against Electric Shock",
                "requirement_summary": "Automatic disconnection of supply shall be achieved through protective earthing, equipotential bonding and correctly rated protective devices.",
                "test_method": "Earth fault loop impedance measurement",
                "tolerance_limit": "Disconnection within the maximum times specified for the circuit type and system earthing arrangement.",
            },
            {
                "clause_no": "Clause 7",
                "clause_title": "Selection of Conductors and Voltage Drop",
                "requirement_summary": "Conductor cross-sections shall be selected for current-carrying capacity, grouping derating and permissible voltage drop.",
                "test_method": "Design calculation review against installed cable schedule",
                "tolerance_limit": "Voltage drop not exceeding 3 percent for lighting and 5 percent for other circuits from the origin of the installation.",
            },
            {
                "clause_no": "Clause 10",
                "clause_title": "Initial Verification and Testing",
                "requirement_summary": "Every installation shall be inspected and tested before being put into service and results recorded.",
                "test_method": "Insulation resistance, continuity, polarity, RCD operation tests",
                "tolerance_limit": "Insulation resistance not less than 1 megohm; RCD tripping within rated time.",
            },
        ],
        "test_methods": [
            {"name": "Insulation Resistance Test", "method_standard": "IS 732 Clause 10", "frequency": "Pre-commissioning", "mandatory": True},
            {"name": "Earth Fault Loop Impedance Test", "method_standard": "IS 732 Clause 10", "frequency": "Pre-commissioning", "mandatory": True},
            {"name": "RCD / RCBO Operation Test", "method_standard": "IS 732 Clause 10", "frequency": "Pre-commissioning", "mandatory": True},
        ],
        "amendments": [
            {"amendment_no": "Amendment No. 1", "date": "2022-08-01", "summary": "Updated references for protective devices and surge protection coordination.", "status": "Active"},
        ],
        "related_standards": [
            {"code": "IS 3043: 2018", "title": "Code of Practice for Earthing", "relation_type": "Companion Safety Code"},
            {"code": "IS 694: 2010", "title": "PVC Insulated Cables up to 450/750 V", "relation_type": "Material Specification"},
        ],
        "keywords": ["wiring installation", "electrical installation", "voltage drop", "RCD", "earth fault loop", "shock protection", "commissioning"],
    },
    {
        "id": "std-is-3043",
        "code": "IS 3043: 2018",
        "title": "Code of Practice for Earthing",
        "category": "Electrotechnical",
        "technical_committee": "ETD 20 Electrical Installations Sectional Committee",
        "ics_code": "29.240.01",
        "status": "current",
        "reaffirmation_year": 2023,
        "gazetted_date": "2018-07-12",
        "qco_mandatory": False,
        "scope": "Covers design and installation of earthing systems, including earth electrodes, earthing conductors, equipotential bonding, soil resistivity assessment and measurement of earth resistance for power installations and substations.",
        "why_recommended_template": "Required wherever earthing, bonding or lightning-protection interfaces form part of an electrical procurement or installation scope.",
        "key_clauses": [
            {
                "clause_no": "Clause 8",
                "clause_title": "Earth Electrode Design",
                "requirement_summary": "Electrode type, material, dimensions and quantity shall be selected from measured soil resistivity to achieve the target earth resistance.",
                "test_method": "Wenner four-electrode soil resistivity survey",
                "tolerance_limit": "Design target commonly 1 ohm for large substations and 5 ohm for LT installations, as specified for the application.",
            },
            {
                "clause_no": "Clause 9",
                "clause_title": "Earthing Conductor Sizing",
                "requirement_summary": "Earthing conductors shall withstand the prospective fault current for the protection clearing time without exceeding permissible temperature.",
                "test_method": "Adiabatic sizing calculation review",
                "tolerance_limit": "Cross-section not less than that derived from the fault current and clearing time.",
            },
            {
                "clause_no": "Clause 12",
                "clause_title": "Measurement of Earth Resistance",
                "requirement_summary": "Earth resistance of installed electrodes shall be measured and recorded before commissioning and periodically thereafter.",
                "test_method": "Fall-of-potential method using earth tester",
                "tolerance_limit": "Measured value within the design target declared for the installation.",
            },
        ],
        "test_methods": [
            {"name": "Soil Resistivity Survey", "method_standard": "IS 3043 Clause 8", "frequency": "Design stage", "mandatory": True},
            {"name": "Earth Resistance Measurement", "method_standard": "IS 3043 Clause 12", "frequency": "Pre-commissioning and periodic", "mandatory": True},
        ],
        "amendments": [],
        "related_standards": [
            {"code": "IS 732: 2019", "title": "Code of Practice for Electrical Wiring Installations", "relation_type": "Companion Installation Code"},
            {"code": "IS 2026 (Part 1): 2011", "title": "Power Transformers - General", "relation_type": "Equipment Interface"},
        ],
        "keywords": ["earthing", "grounding", "earth electrode", "soil resistivity", "bonding", "earth resistance", "substation"],
    },
    {
        "id": "std-is-2026-1",
        "code": "IS 2026 (Part 1): 2011",
        "title": "Power Transformers - Part 1: General",
        "category": "Electrotechnical",
        "technical_committee": "ETD 16 Transformers Sectional Committee",
        "ics_code": "29.180",
        "status": "current",
        "reaffirmation_year": 2021,
        "gazetted_date": "2011-09-15",
        "qco_mandatory": False,
        "scope": "Applies to three-phase and single-phase power transformers, specifying rating plate information, tappings, connection symbols, temperature rise limits, tolerances on guaranteed values and the routine, type and special tests applicable.",
        "why_recommended_template": "Provides the general rating, tolerance and test framework referenced by every distribution and power transformer specification.",
        "key_clauses": [
            {
                "clause_no": "Clause 9",
                "clause_title": "Tolerances on Guaranteed Values",
                "requirement_summary": "Declared losses, impedance and no-load current are subject to the tolerances tabulated in the standard.",
                "test_method": "Loss measurement during routine testing",
                "tolerance_limit": "Total losses tolerance +10 percent of guaranteed total losses; impedance tolerance as tabulated.",
            },
            {
                "clause_no": "Clause 11",
                "clause_title": "Routine, Type and Special Tests",
                "requirement_summary": "Every transformer shall undergo the listed routine tests; type tests apply to representative units.",
                "test_method": "Ratio, polarity, winding resistance, no-load and load loss, separate source withstand tests",
                "tolerance_limit": "All routine test results within declared values and tolerances.",
            },
            {
                "clause_no": "Clause 12",
                "clause_title": "Temperature Rise Limits",
                "requirement_summary": "Top oil and winding temperature rise shall not exceed the limits for the declared cooling method.",
                "test_method": "Temperature rise test by back-to-back or short-circuit method",
                "tolerance_limit": "Top oil rise 50 K and average winding rise 55 K for ONAN oil-immersed transformers.",
            },
        ],
        "test_methods": [
            {"name": "Ratio, Polarity and Vector Group Test", "method_standard": "IS 2026 (Part 1) Clause 11", "frequency": "Routine test", "mandatory": True},
            {"name": "No-Load and Load Loss Measurement", "method_standard": "IS 2026 (Part 1) Clause 11", "frequency": "Routine test", "mandatory": True},
            {"name": "Temperature Rise Test", "method_standard": "IS 2026 (Part 2)", "frequency": "Type test", "mandatory": True},
        ],
        "amendments": [
            {"amendment_no": "Amendment No. 1", "date": "2014-02-01", "summary": "Editorial alignment with IEC 60076-1 clause numbering.", "status": "Active"},
        ],
        "related_standards": [
            {"code": "IS 1180 (Part 1): 2014", "title": "Outdoor Type Oil Immersed Distribution Transformers", "relation_type": "Product Specification"},
            {"code": "IS 3043: 2018", "title": "Code of Practice for Earthing", "relation_type": "Installation Safety Code"},
        ],
        "keywords": ["power transformer", "losses", "temperature rise", "vector group", "routine test", "impedance", "tolerance"],
    },
    # ------------------------------------------------------------- SAFETY & FIRE
    {
        "id": "std-is-15683",
        "code": "IS 15683: 2018",
        "title": "Portable Fire Extinguishers - Performance and Construction - Specification",
        "category": "Safety & Fire",
        "technical_committee": "CED 22 Fire Safety Sectional Committee",
        "ics_code": "13.220.10",
        "status": "current",
        "reaffirmation_year": 2023,
        "gazetted_date": "2018-06-20",
        "qco_mandatory": True,
        "scope": "Specifies construction, performance, marking and testing requirements for portable fire extinguishers of water, foam, powder, carbon dioxide and clean-agent types, including fire rating tests and body strength requirements.",
        "why_recommended_template": "Applies to all portable fire extinguisher procurement, defining fire rating class, discharge performance and body pressure requirements.",
        "key_clauses": [
            {
                "clause_no": "Clause 6",
                "clause_title": "Fire Rating and Extinguishing Performance",
                "requirement_summary": "Each extinguisher shall achieve the declared Class A and Class B fire ratings in the prescribed test fires.",
                "test_method": "Wood crib (Class A) and heptane tray (Class B) fire tests",
                "tolerance_limit": "Declared rating shall be achieved in the required number of successive tests.",
            },
            {
                "clause_no": "Clause 8",
                "clause_title": "Discharge Time and Discharge Efficiency",
                "requirement_summary": "Minimum effective discharge time and residual charge limits shall be met at the declared operating temperature range.",
                "test_method": "Discharge test with weighed residue",
                "tolerance_limit": "Residual charge not more than 10 percent of nominal charge; minimum discharge time as tabulated by capacity.",
            },
            {
                "clause_no": "Clause 10",
                "clause_title": "Body Hydraulic Strength and Burst",
                "requirement_summary": "Extinguisher body shall withstand hydraulic test pressure without leakage or permanent deformation.",
                "test_method": "Hydraulic pressure and burst test",
                "tolerance_limit": "Test pressure as specified for the extinguisher class with no leakage or visible distortion.",
            },
        ],
        "test_methods": [
            {"name": "Fire Rating Test", "method_standard": "IS 15683 Clause 6", "frequency": "Type test", "mandatory": True},
            {"name": "Hydraulic Pressure Test", "method_standard": "IS 15683 Clause 10", "frequency": "Routine test", "mandatory": True},
            {"name": "Discharge Performance Test", "method_standard": "IS 15683 Clause 8", "frequency": "Type test and lot verification", "mandatory": True},
        ],
        "amendments": [
            {"amendment_no": "Amendment No. 1", "date": "2021-03-01", "summary": "Updated clean-agent extinguishing media references and marking requirements.", "status": "Active"},
        ],
        "related_standards": [
            {"code": "IS 2190: 2010", "title": "Selection, Installation and Maintenance of First-Aid Fire Extinguishers - Code of Practice", "relation_type": "Installation Code"},
            {"code": "IS 2925: 1984", "title": "Industrial Safety Helmets", "relation_type": "Site Safety Complement"},
        ],
        "keywords": ["fire extinguisher", "portable extinguisher", "fire rating", "ABC powder", "carbon dioxide", "discharge time", "fire safety"],
    },
    {
        "id": "std-is-15298-2",
        "code": "IS 15298 (Part 2): 2016",
        "title": "Personal Protective Equipment - Part 2: Safety Footwear",
        "category": "Safety & Fire",
        "technical_committee": "CHD 19 Footwear Sectional Committee",
        "ics_code": "13.340.50",
        "status": "current",
        "reaffirmation_year": 2022,
        "gazetted_date": "2016-08-05",
        "qco_mandatory": True,
        "scope": "Specifies basic and additional requirements for safety footwear incorporating protective toecaps designed to give protection against impact of at least 200 J and compression of at least 15 kN, including slip resistance and penetration resistance options.",
        "why_recommended_template": "Applies to safety footwear procurement, fixing toecap impact energy, penetration resistance and slip resistance classes.",
        "key_clauses": [
            {
                "clause_no": "Clause 5.3",
                "clause_title": "Toecap Impact and Compression Resistance",
                "requirement_summary": "Toecap shall resist the specified impact energy and compression load while retaining internal clearance.",
                "test_method": "Impact and compression test on complete footwear",
                "tolerance_limit": "200 J impact and 15 kN compression with minimum internal clearance maintained.",
            },
            {
                "clause_no": "Clause 6.2",
                "clause_title": "Penetration Resistance",
                "requirement_summary": "Where specified, the penetration-resistant insert shall resist a standard nail force without perforation.",
                "test_method": "Penetration test with standard truncated nail",
                "tolerance_limit": "Penetration force not less than 1100 N.",
            },
            {
                "clause_no": "Clause 6.4",
                "clause_title": "Slip Resistance",
                "requirement_summary": "Outsole shall meet the declared slip resistance class on ceramic tile with detergent and/or steel with glycerine.",
                "test_method": "Slip resistance test on standard surfaces",
                "tolerance_limit": "Coefficient of friction not less than the tabulated values for the declared SRA / SRB / SRC class.",
            },
        ],
        "test_methods": [
            {"name": "Toecap Impact and Compression Test", "method_standard": "IS 15298 (Part 1)", "frequency": "Type test", "mandatory": True},
            {"name": "Penetration Resistance Test", "method_standard": "IS 15298 (Part 1)", "frequency": "Type test", "mandatory": False},
            {"name": "Slip Resistance Test", "method_standard": "IS 15298 (Part 1)", "frequency": "Type test", "mandatory": True},
        ],
        "amendments": [
            {"amendment_no": "Amendment No. 1", "date": "2019-11-01", "summary": "Clarified marking of protection categories and slip resistance classes.", "status": "Active"},
        ],
        "related_standards": [
            {"code": "IS 2925: 1984", "title": "Industrial Safety Helmets", "relation_type": "PPE Set Complement"},
            {"code": "IS 3521 (Part 1): 2021", "title": "Personal Fall Protection - Full Body Harnesses", "relation_type": "PPE Set Complement"},
        ],
        "keywords": ["safety shoes", "safety footwear", "toecap", "penetration resistance", "slip resistance", "PPE", "200 J"],
    },
    {
        "id": "std-is-3521-2",
        "code": "IS 3521 (Part 2): 2021",
        "title": "Personal Fall Protection - Part 2: Lanyards and Energy Absorbers",
        "category": "Safety & Fire",
        "technical_committee": "PGD 32 Personal Protective Equipment Sectional Committee",
        "ics_code": "13.340.60",
        "status": "current",
        "reaffirmation_year": 2026,
        "gazetted_date": "2021-10-08",
        "qco_mandatory": True,
        "scope": "Specifies requirements, test methods, marking and information supplied by the manufacturer for lanyards and energy absorbers forming part of personal fall arrest systems, including dynamic performance and static strength.",
        "why_recommended_template": "Required wherever fall arrest lanyards or shock absorbers are procured alongside full body harnesses for work at height.",
        "key_clauses": [
            {
                "clause_no": "Clause 4.3",
                "clause_title": "Dynamic Performance",
                "requirement_summary": "Energy absorber shall limit arrest force on the user and the arrest distance during the dynamic drop test.",
                "test_method": "Dynamic drop test with rigid or torso mass",
                "tolerance_limit": "Arrest force not exceeding 6 kN with arrest distance within the declared limit.",
            },
            {
                "clause_no": "Clause 4.4",
                "clause_title": "Static Strength",
                "requirement_summary": "Lanyard assembly with terminations shall withstand the specified static load without rupture.",
                "test_method": "Static tensile test on complete assembly",
                "tolerance_limit": "Static strength not less than 22 kN for textile lanyards as specified.",
            },
            {
                "clause_no": "Clause 6",
                "clause_title": "Marking and Information Supplied",
                "requirement_summary": "Each item shall carry permanent marking of standard reference, batch, year of manufacture and maximum permitted length.",
                "test_method": "Visual verification of marking legibility after conditioning",
                "tolerance_limit": "Marking legible after abrasion and conditioning; total lanyard length including terminations not exceeding 2 m.",
            },
        ],
        "test_methods": [
            {"name": "Dynamic Drop Test", "method_standard": "IS 3521 (Part 2) Clause 4.3", "frequency": "Type test", "mandatory": True},
            {"name": "Static Strength Test", "method_standard": "IS 3521 (Part 2) Clause 4.4", "frequency": "Type test and lot verification", "mandatory": True},
        ],
        "amendments": [],
        "related_standards": [
            {"code": "IS 3521 (Part 1): 2021", "title": "Personal Fall Protection - Full Body Harnesses", "relation_type": "Part of Series"},
            {"code": "IS 2925: 1984", "title": "Industrial Safety Helmets", "relation_type": "PPE Set Complement"},
        ],
        "keywords": ["fall arrest", "lanyard", "energy absorber", "shock absorber", "work at height", "harness", "22 kN", "PPE"],
    },
]
